
<style type="text/css">
	body {
		font-family:Arial, Helvetica, sans-serif;
		font-size:12px;
		margin:30px }
	.pagetitle {
		font-size:16px }
	.sectiontitle {
		font-size:14px }
</style>
<head>
	<title>PANDUAN UNTUK USER</title>	<script type="text/javascript" src="http://studentsman5.url.ph/geci_assets/7b18b0c981a1fdaade30b4be075679e2/jquery-1.7.2.min.js"></script>
</head>
<center><b><h1>PANDUAN USER</h1></b></center>
<p class="sectiontitle"><strong>A.&nbsp; PANDUAN TAB MENU "HOME"</strong></p>
<br>PADA PANDUAN USER UNTUK TAB MENU HOME AKAN DIJELASKAN DENGAN MENGGUNAKAN KOTAK WARNA, YANG SETIAP WARNA NYA SUDAH DIBEDAKAN SESUAI DENGAN FUNGSI DARI MASING MASING FITUR.DAPAT DILIHAT DENGAN GAMBAR DI BAWAH INI :</br> <br> 
<img src="../../template/images/home.png"/></br>
<br> BERIKUT PENJELASAN DARI MASING – MASING FITUR SESUAI DENGAN WARNA YANG DIGUNAKAN :</br>
<ol>
	<li>KOTAK BERWARNA BIRU : MERUPAKAN IDENTITAS
DARI USER YANG TELAH ME LOG-IN DALAM SISTEM INFORMASI PERPUSTAKAAN.
</li><br>
	<li>KOTAK BERWARNA MERAH : MERUPAKAN FITUR DARI INFORMASI BUKU BARU, YANG DIMANA TERPAMPANG JUDUL DARI BUKU BARU YANG TERSEDIA PADA PERPUSTAKAAN. PADA FITUR INI, INFORMASI BUKU BARU AKAN TERBAHARUI / TERUPDATE UNTUK SETIAP BULAN.</li><br>
  <li>KOTAK BERWARNA KUNING : MERUPAKAN FITUR DARI HISTORY PEMINJAMAN BUKU, YANG MANA PADA FITUR INI MENERANGKAN INFORMASI PEMINJAMAN BUKU YANG PERNAH DILAKUKAN SEBELUMNYA OLEH USER. ADAPUN INFORMASI YANG TERTERA PADA FITUR INI ADALAH NAMA BUKU, TANGGAL PEMINJAMAN BUKU DAN TANGGAL PENGEMBALIAN BUKU.</li><br>
	<li>KOTAK BERWARNA HIJAU : MERUPAKAN FITUR DARI DAFTAR BOOKING BUKU, DIMANA PADA FITUR INI DIJELASKAN INFORMASI MENGENAI DAFTAR BUKU YANG TELAH DI BOOKING OLEH USER DAN AKAN BERTAMBAH SESUAI DENGAN JUMLAH BUKU YANG TELAH DI BOOKING OLEH USER. ADAPUN INFORMASI YANG TERTERA PADA FITUR INI ADALAH NAMA BUKU YANG DIBOOKING DAN TANGGAL TERSEDIA UNTUK MEMBOOKING BUKU.</li><br>

</ol>
<p class="sectiontitle"><strong>B.&nbsp; PANDUAN USER PEMINJAMAN BUKU</strong></p>
<br>PADA PANDUAN INI, AKAN DIJELASKAN BAGAIMANA URUTAN SISTEMATIS DALAM MELAKUKAN PEMINJAMAN BUKU PADA SISTEM INFORMASI PERPUSTAKAAN. BERIKUT ADALAH LANGKAH LANGKAH MELAKUKAN PEMINJAMAN BUKU :</br> <br>
	<ol>
		<li>USER MEMBUKA TAB MENU PEMINJAMAN BUKU, YANG AKAN TERLIHAT SEPERTI GAMBAR DIBAWAH INI 
		</li><br>
<img src="../../template/images/buku1.png"/><br>
		<br><li>USER MENGINPUT KEYWORD DARI JUDUL BUKU YANG INGIN DIKEHENDAKI. LALU MENEKAN TOMBOL SUBMIT. SEBAGAI CONTOH DIINPUTKAN KEYWORD DARI JUDUL BUKU YAITU PEMROGRAMAN. MAKA AKAN TAMPIL SEPERTI GAMBAR DI BAWAH INI.</li><br>
<img src="../../template/images/buku2.png"/><br>
		<br><li>BILA SUDAH MENEKAN TOMBOL SUBMIT PADA LAYAR, MAKA SISTEM AKAN MENAMPILKAN INFORMASI DARI BUKU YANG DICARI. ADAPUN INFORMASI BUKU YANG TERPAMPANG YAITU ID BUKU, NAMA BUKU, PENGARANG, PENERBIT, KATEGORI BUKU, STOK BUKU, KETERSEDIAAN BUKU, DAN PINJAM (BOOKING) YANG DAPAT DILIHAT PADA GAMBAR DIBAWAH INI</li><br>
<img src="../../template/images/buku3.png"/><br>
<br><li>PADA LANGKAH INI USER DAPAT HANYA MELAKUKAN PENCARIAN BUKU ELECTRONIC UNTUK MENGETAHUI KETERSEDIAAN BUKU DAN DAPAT MELAKUKAN PINJAM (BOOKING) BUKU DENGAN MENEKAN FITUR MENU PINJAM BUKU PADA LAYAR DAN APABILA USER SUDAH MELAKUKAN PINJAM BUKU (BOOKING BUKU) MAKA SISTEM AKAN MENAMPILKAN RESPON BAHWA BOOKING TELAH BERHASIL SEPERTI GAMBAR DIBAWAH INI</li><br>
<img src="../../template/images/buku4.png"/>
	</ol>